### PR TITLE
Fixed reactivity of the $asyncComputed properties

### LINKED ISSUE #52: $asyncComputed.prop.updating is only set on intial evaluation
The `updating` field is only set when the computed property is first evaluated. After, if the property is re-evaluated, the field is not updated.

### PR DESCRIPTION
**Pull request by mtorromeo**
This makes `$asyncComputed` reactive by turning it into a property of `$data` and manipulating it with `Vue.set`.

This should fix #52 and #56.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -19,15 +19,21 @@ const AsyncComputed = {
...
       beforeCreate () {
         const optionData = this.$options.data
         const asyncComputed = this.$options.asyncComputed || {}
-        this.$asyncComputed = {}
-
-        if (!Object.keys(asyncComputed).length) return
 
         if (!this.$options.computed) this.$options.computed = {}
 
+        this.$options.computed.$asyncComputed = () => this.$data._asyncComputed
```
Comment (mtorromeo) [inline src/index.js]: Note that I had to implement a little hack here using `_asyncComputed` in `$data` and a corresponding `$asyncComputed` computed property to maintain backwards compatibility. This is necessary since Vue does not proxy properties that start with `_` or `$`.

Alternatives, if backwards compatibility is not needed are:
1. Rename `$asyncComputed` as simply `asyncComputed`.
2. Keep only `$asyncComputed` in data instead of `_asyncComputed`, drop the unnecessary computed property and document that it should be accessed as `this.$data.$asyncComputed`.

**Comment by mtorromeo** [comment]
@foxbenjaminfox do you think you could take a look at this, please?

Happy new year!

**Comment by foxbenjaminfox** [comment]
Sorry that it took me a bit of time to come back around to this project. I've merged the PR, and soon I'll release a version to NPM with the fix.

**Comment by mtorromeo** [comment]
It's cool, thanks for merging!
